name: Daily Run

on:
  schedule:
    - cron: '0 22 * * *' # Run at 10 PM Kuwait time every day
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # 1. Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 2. Set up Google credentials
      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > ./credentials/real-estate-property-scraper-4d9f71a7ded4.json

      # 3. Install Playwright dependencies and browsers
      - name: Install Playwright Browsers
        run: |
          npm install -g playwright
          playwright install

      # 4. Install dependencies (e.g., pandas, playwright, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run the scraper
      - name: Run Scraper
        run: |
          python main.py

      # 6. Upload the results to Google Drive (assuming the credentials and saving logic is set up)
      - name: Save Results to Google Drive
        run: |
          python save_to_drive.py
