name: Scraper Workflow

on:
  schedule:
    - cron: '5 0 * * *' # Runs at 12:05 AM UTC every day

  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright for Python
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install

      # - name: Set GCLOUD_KEY_JSON
      #   env:
      #     GCLOUD_KEY_JSON: ${{ secrets.GCLOUD_KEY_JSON }}
      #   run: |
      #     echo "Google Cloud credentials are set."

      # - name: Run the Scraper
      #   run: |
      #     python main.py
      - name: Run the scraper
        env:
          GCLOUD_KEY_JSON: ${{ secrets.GCLOUD_KEY_JSON }}
        run: |
          python main.py
      - name: Cleanup
        run: |
          # Any cleanup steps (optional)
